spring:
 datasource:
  url: jdbc:postgresql://postgres:5432/vjshow
  username: postgres
  password: 123456
  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 300000
    max-lifetime: 600000
    keepalive-time: 30000
    connection-timeout: 20000
    validation-timeout: 5000
		# Quan trọng: Không để Hikari sập ngay lập tức nếu DB chưa sẵn sàng
    initialization-fail-timeout: 0
    connection-test-query: SELECT 1
 jpa:
  hibernate:
   ddl-auto: create
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    default-schema: public
 security:
   oauth2:
    client:
     registration:
      google:
       client-id: 1041269453688-1341q1go2rcmn3lkeqfk3jul81apd5fk.apps.googleusercontent.com
       client-secret: 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
       scope:
        - email
        - profile
       redirect-uri: https://vjshow.vn/login/oauth2/code/google
       #redirect-uri: http://localhost:8080/login/oauth2/code/google
      facebook:
       client-id: 2564719860596086
       client-secret: d9c8a76434d1689e3ebcd1a4bee53eb8
       scope:
         - email
         - public_profile
     provider:
      facebook:
       authorization-uri: https://www.facebook.com/v17.0/dialog/oauth
       token-uri: https://graph.facebook.com/v17.0/oauth/access_token
       user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
       user-name-attribute: id
 servlet:
  multipart:
   max-file-size: 500MB
   max-request-size: 500MB
server:
  forward-headers-strategy: native
storage:
  r2:
    access-key: 7476a0b5b996b0246f2b0f1fb2d3eeb8
    secret-key: 1f68525330a3f3241abc7361a6dc6eb3abd6740d8fa2cc875dc9b079418b8073
    endpoint: https://f2cf3a00591888eeaac9767d3bc1881a.r2.cloudflarestorage.com
    bucket: vjshow
    public-url: https://cdn.vjshow.vn
worker:
  url: http://queue-api:3001
logging:
   level:
     org.hibernate.SQL: DEBUG
     org.hibernate.orm.jdbc.bind: TRACE
     org.springframework.orm.jpa: DEBUG
